Handle version folders for file spaces
owncloud/encryption pull request #301
Opened 2021-08-12 11:30 UTC by JammingBen

2021-08-12 12:15 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiCoreMKey-50-34-master-mysql8.0-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/encryption/2039/65/1

2021-08-16 14:34 UTC, ownclouders commented
:boom: Acceptance tests pipeline <strong>apiCoreMKey-50-34-master-mysql8.0-php7.2</strong> failed. The build has been cancelled.

https://drone.owncloud.com/owncloud/encryption/2046/65/1

2021-10-12 09:47 UTC, DeepDiver1975 requested changes

2021-11-16 14:14 UTC, JammingBen commented
Superseded by https://github.com/owncloud/encryption/pull/307.

2021-11-16 14:14 UTC, closed without merging